# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import predictionService_pb2 as predictionService__pb2


class PricePredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predictPrices = channel.unary_unary(
                '/predictionService.PricePredictor/predictPrices',
                request_serializer=predictionService__pb2.PriceRequest.SerializeToString,
                response_deserializer=predictionService__pb2.PriceResponse.FromString,
                )


class PricePredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predictPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricePredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predictPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.predictPrices,
                    request_deserializer=predictionService__pb2.PriceRequest.FromString,
                    response_serializer=predictionService__pb2.PriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predictionService.PricePredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PricePredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predictPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predictionService.PricePredictor/predictPrices',
            predictionService__pb2.PriceRequest.SerializeToString,
            predictionService__pb2.PriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
