# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictionService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17predictionService.proto\x12\x11predictionService\"\"\n\x0cPriceRequest\x12\x12\n\nobjectName\x18\x01 \x01(\t\"\x1e\n\rPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x32\x64\n\x0ePricePredictor\x12R\n\rpredictPrices\x12\x1f.predictionService.PriceRequest\x1a .predictionService.PriceResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictionService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICEREQUEST._serialized_start=46
  _PRICEREQUEST._serialized_end=80
  _PRICERESPONSE._serialized_start=82
  _PRICERESPONSE._serialized_end=112
  _PRICEPREDICTOR._serialized_start=114
  _PRICEPREDICTOR._serialized_end=214
# @@protoc_insertion_point(module_scope)
